# Generated by Django 5.2.14 on 2026-06-16 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Identificador interno')),
                ('ordem', models.PositiveSmallIntegerField(verbose_name='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Status do workflow',
                'verbose_name_plural': 'Status do workflow',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retranca', models.CharField(help_text='Identificador editorial da imagem.', max_length=120, verbose_name='Retranca')),
                ('nome_obra', models.CharField(max_length=200, verbose_name='Nome da obra')),
                ('volume_ano_modulo', models.CharField(blank=True, max_length=60, verbose_name='Volume / Ano / Módulo')),
                ('componente_curricular', models.CharField(blank=True, max_length=100, verbose_name='Componente curricular')),
                ('capitulo_unidade', models.CharField(blank=True, max_length=100, verbose_name='Capítulo / Unidade')),
                ('etapa', models.CharField(choices=[('AD', 'AD'), ('FT', 'FT — Fechamento Técnico'), ('Original', 'Original'), ('P1', 'P1 — Prova 1'), ('P2', 'P2 — Prova 2'), ('P3', 'P3 — Prova 3')], default='AD', max_length=10, verbose_name='Etapa')),
                ('nome_arquivo', models.CharField(blank=True, max_length=255, verbose_name='Nome do arquivo')),
                ('tamanho_arquivo', models.CharField(blank=True, max_length=30, verbose_name='Tamanho do arquivo')),
                ('dimensoes', models.CharField(blank=True, help_text='Ex: 1920x1080 px', max_length=30, verbose_name='Dimensões')),
                ('resolucao', models.CharField(blank=True, help_text='Ex: 300 dpi', max_length=20, verbose_name='Resolução')),
                ('tamanho_fisico', models.CharField(blank=True, help_text='Ex: 15x10 cm', max_length=30, verbose_name='Tamanho físico')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='Prazo final')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagens_cadastradas', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagens_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imagens', to='core.statusworkflow', verbose_name='Status atual')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Descricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_descricao', models.DateTimeField(blank=True, null=True, verbose_name='Início da descrição')),
                ('fim_descricao', models.DateTimeField(blank=True, null=True, verbose_name='Fim da descrição')),
                ('inicio_conferencia', models.DateTimeField(blank=True, null=True, verbose_name='Início da conferência')),
                ('fim_conferencia', models.DateTimeField(blank=True, null=True, verbose_name='Fim da conferência')),
                ('inicio_revisao', models.DateTimeField(blank=True, null=True, verbose_name='Início da revisão final')),
                ('fim_revisao', models.DateTimeField(blank=True, null=True, verbose_name='Fim da revisão final')),
                ('finalizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('descritor_bloqueado', models.BooleanField(default=False, help_text='Bloqueado automaticamente após o primeiro salvamento.', verbose_name='Descritor bloqueado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações internas')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descricoes_coordenadas', to=settings.AUTH_USER_MODEL, verbose_name='Coordenador')),
                ('descritor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descricoes_produzidas', to=settings.AUTH_USER_MODEL, verbose_name='Descritor')),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descricoes_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisor')),
                ('imagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='descricao', to='core.imagem', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Descrição',
                'verbose_name_plural': 'Descrições',
            },
        ),
        migrations.CreateModel(
            name='HistoricoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('imagem_cadastrada', 'Imagem cadastrada'), ('tarefa_atribuida', 'Tarefa atribuída'), ('descricao_iniciada', 'Descrição iniciada'), ('descricao_salva', 'Descrição salva'), ('descritor_bloqueado', 'Descritor bloqueado'), ('liberado_conferencia', 'Liberado para conferência'), ('conferencia_iniciada', 'Conferência iniciada'), ('conferencia_concluida', 'Conferência concluída'), ('devolvido_correcao', 'Devolvido para correção'), ('descritor_liberado', 'Acesso do descritor liberado'), ('revisao_iniciada', 'Revisão final iniciada'), ('revisao_concluida', 'Revisão final concluída'), ('descricao_finalizada', 'Descrição finalizada'), ('enviado_fotoweb', 'Enviado ao FotoWeb'), ('status_alterado', 'Status alterado')], max_length=40, verbose_name='Tipo de ação')),
                ('observacao', models.TextField(blank=True, help_text='Justificativa ou detalhe da ação.', verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora')),
                ('descricao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico', to='core.descricao', verbose_name='Descrição')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.imagem', verbose_name='Imagem')),
                ('novo_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_novo', to='core.statusworkflow', verbose_name='Novo status')),
                ('status_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_anterior', to='core.statusworkflow', verbose_name='Status anterior')),
            ],
            options={
                'verbose_name': 'Item de histórico',
                'verbose_name_plural': 'Histórico',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Trecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(verbose_name='Ordem')),
                ('texto', models.TextField(verbose_name='Texto do trecho')),
                ('idioma_codigo', models.CharField(default='por', help_text='Código ISO 639-3. Ex: por (Português), eng (Inglês).', max_length=10, verbose_name='Código do idioma')),
                ('idioma_nome', models.CharField(default='Português', max_length=100, verbose_name='Nome do idioma')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='core.descricao', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Trecho',
                'verbose_name_plural': 'Trechos',
                'ordering': ['ordem'],
            },
        ),
    ]
