# Generated by Django 5.2.14 on 2026-06-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_statusworkflow_imagem_descricao_historicoitem_trecho'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='caminho_arquivo',
            field=models.CharField(blank=True, help_text='Caminho ou referência de onde o arquivo está armazenado.', max_length=500, verbose_name='Caminho do arquivo'),
        ),
    ]
