# Generated by Django 5.2.14 on 2026-06-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imagem_caminho_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='url_fotoweb',
            field=models.CharField(blank=True, help_text='Link para a página da imagem no FotoWeb (preview do asset).', max_length=500, verbose_name='URL no FotoWeb'),
        ),
    ]
