# Generated by Django 5.2.14 on 2026-06-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_imagem_url_fotoweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='url_pdf',
            field=models.CharField(blank=True, help_text='Link para o PDF relacionado no FotoWeb.', max_length=500, verbose_name='URL do PDF no FotoWeb'),
        ),
    ]
