# Generated by Django 5.2.14 on 2026-07-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_imagem_url_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='retranca',
            field=models.CharField(db_index=True, help_text='Identificador editorial da imagem.', max_length=120, unique=True, verbose_name='Retranca'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='url_pdf',
            field=models.CharField(blank=True, help_text='Link para o PDF da imagem.', max_length=500, verbose_name='URL do PDF'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='volume_ano_modulo',
            field=models.CharField(blank=True, max_length=60, verbose_name='Volume/Ano/Módulo'),
        ),
    ]
