# Generated by Django 5.2.14 on 2026-07-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_imagem_retranca_alter_imagem_url_pdf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusworkflow',
            options={'ordering': ['ordem'], 'verbose_name': 'Trecho', 'verbose_name_plural': 'Trechos'},
        ),
        migrations.AlterUniqueTogether(
            name='statusworkflow',
            unique_together={('descricao', 'ordem')},
        ),
    ]
