# Generated by Django 5.2.14 on 2026-07-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_statusworkflow_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descricao',
            name='fim_conferencia',
        ),
        migrations.RemoveField(
            model_name='descricao',
            name='fim_descricao',
        ),
        migrations.RemoveField(
            model_name='descricao',
            name='fim_revisao',
        ),
        migrations.RemoveField(
            model_name='descricao',
            name='finalizado_em',
        ),
        migrations.RemoveField(
            model_name='descricao',
            name='inicio_conferencia',
        ),
        migrations.RemoveField(
            model_name='descricao',
            name='inicio_descricao',
        ),
        migrations.RemoveField(
            model_name='descricao',
            name='inicio_revisao',
        ),
    ]
