# Generated by Django 5.2.14 on 2026-07-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_descricao_fim_conferencia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusworkflow',
            options={'ordering': ['ordem'], 'verbose_name': 'Status do workflow', 'verbose_name_plural': 'Status do workflow'},
        ),
        migrations.AlterUniqueTogether(
            name='statusworkflow',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='trecho',
            unique_together={('descricao', 'ordem')},
        ),
    ]
