# Generated by Django 5.2.14 on 2026-07-06 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_statusworkflow_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='importacao_id',
            field=models.UUIDField(blank=True, editable=False, help_text='Identifica todas as imagens vindas do mesmo upload de .xlsx, permitindo isolar o lote de origem na tela de organização em lotes.', null=True, verbose_name='ID da importação'),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Ex: 'Matemática V2 2026'.", max_length=100, unique=True, verbose_name='Nome do lote')),
                ('descricao', models.CharField(blank=True, help_text='Observação opcional sobre o critério usado para formar o lote.', max_length=255, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ativo', models.BooleanField(default=True, help_text='Exclusão lógica: lotes inativos não devem ser exibidos nas listagens.', verbose_name='Ativo')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='imagem',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagens', to='core.lote', verbose_name='Lote'),
        ),
    ]
