# Generated by Django 5.2.14 on 2026-07-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_imagem_importacao_id_lote_imagem_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='pagamento_descritor',
            field=models.CharField(choices=[('contabilizado', 'Contabilizado'), ('pago', 'Pago')], default='contabilizado', max_length=20, verbose_name='Pagamento — Descritor'),
        ),
        migrations.AddField(
            model_name='imagem',
            name='pagamento_revisor',
            field=models.CharField(choices=[('contabilizado', 'Contabilizado'), ('pago', 'Pago')], default='contabilizado', max_length=20, verbose_name='Pagamento — Revisor'),
        ),
        migrations.AlterField(
            model_name='historicoitem',
            name='tipo_acao',
            field=models.CharField(choices=[('imagem_cadastrada', 'Imagem cadastrada'), ('tarefa_atribuida', 'Tarefa atribuída'), ('descricao_iniciada', 'Descrição iniciada'), ('descricao_salva', 'Descrição salva'), ('descritor_bloqueado', 'Descritor bloqueado'), ('liberado_conferencia', 'Liberado para conferência'), ('conferencia_iniciada', 'Conferência iniciada'), ('conferencia_concluida', 'Conferência concluída'), ('devolvido_correcao', 'Devolvido para correção'), ('descritor_liberado', 'Acesso do descritor liberado'), ('revisao_iniciada', 'Revisão final iniciada'), ('revisao_concluida', 'Revisão final concluída'), ('descricao_finalizada', 'Descrição finalizada'), ('enviado_fotoweb', 'Enviado ao FotoWeb'), ('status_alterado', 'Status alterado'), ('pagamento_atualizado', 'Status de pagamento atualizado')], max_length=40, verbose_name='Tipo de ação'),
        ),
    ]
