# Generated by Django 5.2.14 on 2026-07-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_imagem_pagamento_descritor_imagem_pagamento_revisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='prazo',
            field=models.DateField(blank=True, help_text='Ao salvar, este prazo é aplicado a todas as imagens do lote.', null=True, verbose_name='Prazo do lote'),
        ),
    ]
