# Generated by Django 5.2.14 on 2026-07-23 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_usuario_managers_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_aprovados', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado/recusado por'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='decidido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da decisão'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='observacao_decisao',
            field=models.TextField(blank=True, help_text='Motivo da recusa ou observação do administrador.', verbose_name='Observação da decisão'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='situacao',
            field=models.CharField(choices=[('pendente', 'Pendente de aprovação'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='aprovado', help_text="Solicitações pela tela pública nascem como 'Pendente'.", max_length=20, verbose_name='Situação do cadastro'),
        ),
    ]
