# Generated by Django 5.2.14 on 2026-07-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_usuario_aprovado_por_usuario_decidido_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusworkflow',
            name='exige_atribuicao',
            field=models.BooleanField(default=False, help_text='Se marcado, o coordenador precisa escolher um responsável antes de avançar.', verbose_name='Exige atribuição do coordenador'),
        ),
        migrations.AddField(
            model_name='statusworkflow',
            name='is_final',
            field=models.BooleanField(default=False, help_text='O status que encerra o fluxo (nada avança a partir dele).', verbose_name='Status final'),
        ),
        migrations.AddField(
            model_name='statusworkflow',
            name='is_inicial',
            field=models.BooleanField(default=False, help_text='O status em que as imagens entram ao serem importadas.', verbose_name='Status inicial'),
        ),
        migrations.AddField(
            model_name='statusworkflow',
            name='perfil_responsavel',
            field=models.CharField(choices=[('descritor', 'Descritor'), ('revisor', 'Revisor'), ('coordenador', 'Coordenador')], default='descritor', help_text='Qual perfil trabalha neste status.', max_length=20, verbose_name='Perfil responsável'),
        ),
    ]
