# Generated by Django 5.2.14 on 2026-07-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_statusworkflow_exige_atribuicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descricao',
            name='revisor_bloqueado',
            field=models.BooleanField(default=False, help_text='Bloqueado automaticamente após a conferência ser concluída.', verbose_name='Revisor bloqueado'),
        ),
        migrations.AlterField(
            model_name='historicoitem',
            name='tipo_acao',
            field=models.CharField(choices=[('imagem_cadastrada', 'Imagem cadastrada'), ('tarefa_atribuida', 'Tarefa atribuída'), ('descricao_iniciada', 'Descrição iniciada'), ('descricao_salva', 'Descrição salva'), ('descritor_bloqueado', 'Descritor bloqueado'), ('revisor_bloqueado', 'Acesso do revisor bloqueado'), ('liberado_conferencia', 'Liberado para conferência'), ('conferencia_iniciada', 'Conferência iniciada'), ('conferencia_concluida', 'Conferência concluída'), ('devolvido_correcao', 'Devolvido para correção'), ('descritor_liberado', 'Acesso do descritor liberado'), ('revisor_liberado', 'Acesso do revisor liberado'), ('revisao_iniciada', 'Revisão final iniciada'), ('revisao_concluida', 'Revisão final concluída'), ('descricao_finalizada', 'Descrição finalizada'), ('enviado_fotoweb', 'Enviado ao FotoWeb'), ('status_alterado', 'Status alterado'), ('pagamento_atualizado', 'Status de pagamento atualizado')], max_length=40, verbose_name='Tipo de ação'),
        ),
    ]
