# Generated by Django 5.2.14 on 2026-07-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_descricao_revisor_bloqueado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='pronto_para_lote',
            field=models.BooleanField(default=False, help_text='Marca que o usuário já concluiu esta imagem e está aguardando o envio do lote inteiro, sem avançar o status individualmente.', verbose_name='Pronto para envio em lote'),
        ),
    ]
