# Generated by Django 5.2.14 on 2026-08-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_imagem_pronto_para_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='nome',
            field=models.CharField(help_text="Ex: 'MAT V2'.", max_length=100, unique=True, verbose_name='Nome do lote'),
        ),
    ]
