# Generated by Django 5.2.14 on 2026-09-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_lote_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusworkflow',
            name='avanca_ao_abrir',
            field=models.BooleanField(default=False, help_text='Se marcado, a tarefa avança automaticamente para o próximo status ao ser aberta pelo responsável.', verbose_name='Avança ao abrir'),
        ),
        migrations.AddField(
            model_name='statusworkflow',
            name='conferencia_concluida',
            field=models.BooleanField(default=False, help_text='Identifica que este status representa a conclusão da etapa de conferência.', verbose_name='Conferência concluída'),
        ),
        migrations.AddField(
            model_name='statusworkflow',
            name='descricao_concluida',
            field=models.BooleanField(default=False, help_text='Identifica que este status representa a conclusão da etapa de descrição.', verbose_name='Descrição concluída'),
        ),
        migrations.AddField(
            model_name='statusworkflow',
            name='permite_edicao',
            field=models.BooleanField(default=False, help_text='Se marcado, o perfil responsável pode editar a descrição neste status.', verbose_name='Permite edição'),
        ),
        migrations.AddField(
            model_name='statusworkflow',
            name='revisao_concluida',
            field=models.BooleanField(default=False, help_text='Identifica que este status representa a conclusão da etapa de revisão.', verbose_name='Revisão concluída'),
        ),
    ]
