# Generated by Django 5.2.14 on 2026-10-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_statusworkflow_avanca_ao_abrir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='data_efetiva',
            field=models.DateField(blank=True, help_text='Data em que todas as imagens ativas do lote chegaram ao status final. É preenchida automaticamente, mas pode ser ajustada pela coordenação.', null=True, verbose_name='Data efetiva'),
        ),
        migrations.AddField(
            model_name='lote',
            name='data_prevista',
            field=models.DateField(blank=True, help_text='Previsão de conclusão do lote.', null=True, verbose_name='Data prevista'),
        ),
    ]
