# Generated by Django 5.2.14 on 2026-10-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_lote_data_efetiva_lote_data_prevista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='prazo',
        ),
    ]
